theme: minima
title: Additional Results for Paper 11658 (NeurIPS 2021 submission)
description: Efficient Refinement of Convex Relaxations for Branch and Bound based Neural Network Verification (Paper ID 11658)
author:
  name: Anonymous Authors
  email: anonymous@openreview.net
